name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      working-directory: showroom
      run: |
        pip install -e ..
        pip install -r requirements.txt
    - name: Generate static site
      working-directory: showroom
      run: |
        python manage.py build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./showroom/build
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4